# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LFF4Fg6EMrDiYV0jmmzvXhaP5TEE9z2-
"""

nombre=input("Escribe tu nombre:" ),
nota=float(input("Escribe tu nota: "))

def mostrar_estado(nombre, nota):
  if nota>=4:
    estado="aprobo el ramo"

  else:
    estado="reprobo el ramo"
    print("estado:", estado)

mostrar_estado(nombre, nota)

def calcular_promedio(notas):
  total=sum(notas)

  prom= total/len(notas)
  return round(prom, 1)

notas_ana=[6.5, 5.8, 7.0]
prom_ana=calcular_promedio(notas_ana)

print(f"Promedio: {prom_ana}")

def mostrar_menu():
  print("[1]°C->°F")
  print("[2]°F->°C")
  print("[3]Salir")

mostrar_menu()

def pedir_temperatura():
  temp=float(input("Ingrese la temperatura: "))

  return round(temp, 1)

pedir_temperatura()

def mostrar_resultado(orig, conv, ud):
  print(orig)
  print(conv)
  print(ud)

mostrar_resultado(3.0, 40, "CF")

c=float(input("Ingrese la temperatura en CELSIUS: "))

def celsius_a_fahrenheit(c):
  return (c* 9/5) + 32

celsius_a_fahrenheit(c)

f=float(input("Ingrse la temp en FAHRENHEIT"))

def fahrenheit_a_celsius(f):
  return (f-32) *5/9

fahrenheit_a_celsius(f)