# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cDI7emigs5D63C8cWaD1wx7FxmJG7Ie
"""

print("BIENVENIDO AL REGISTRO DE INFORMACION!")
print("A continuacion ingresa tus datos: ")
contacto={
        "Nombre":input("Ingresa tu nombre: "),
        "Telefono":int(input("Ingresa tu numero: ")),
        "Email":input("Ingresa tu correo: "),
        "Edad":int(input("Ingresa tu edad: "))
}

while True:

  print("-----MENU-----")

  print("1. Ver ficha")
  print("2. Editar dato")
  print("Salir")

  opc=int(input("Ingresa una opcion: "))

  if opc==1:
    print("[1]Su nombre es:", contacto["Nombre"])
    print("[2]Su telefono es:", contacto["Telefono"])
    print("[3]Su email es:", contacto["Email"])
    print("[4]Su edad es:", contacto["Edad"])

  elif opc==2:
    campo=input("Que campo deseas modificar? ")
    nuevo=input("Ingrese el nuevo dato: ")
    contacto[campo]=nuevo

  elif opc==3:
    print("Saliendo...")
    break